# Generated by Django 3.0.7 on 2020-06-29 11:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20200629_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='customer_designation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='desigs', to='dashboard.Designation'),
        ),
    ]
