# Generated by Django 3.0.7 on 2020-06-30 19:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20200629_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_discount_amount', models.IntegerField()),
                ('total_discoutn_percentage', models.IntegerField()),
                ('total_amount', models.BigIntegerField()),
                ('remarks', models.TextField()),
                ('date', models.DateField(default=datetime.date.today)),
                ('is_updated', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateField(default=datetime.date.today)),
                ('updated_on', models.DateField(null=True)),
                ('deleted_on', models.DateField(null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Customers')),
            ],
        ),
        migrations.CreateModel(
            name='QuotationsDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(max_length=250)),
                ('unit', models.IntegerField()),
                ('rate', models.IntegerField()),
                ('discount_percentage', models.IntegerField()),
                ('discount_amount', models.IntegerField()),
                ('net_amount', models.BigIntegerField()),
                ('is_updated', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateField(default=datetime.date.today)),
                ('updated_on', models.DateField(null=True)),
                ('deleted_on', models.DateField(null=True)),
                ('quatation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Quotations')),
            ],
        ),
    ]
