# Generated by Django 3.0.7 on 2020-07-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_quotations_quotationsdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotations',
            name='remarks',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='quotations',
            name='total_amount',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quotations',
            name='total_discount_amount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='quotations',
            name='total_discoutn_percentage',
            field=models.IntegerField(default=0),
        ),
    ]
