# Generated by Django 3.0.7 on 2020-07-01 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20200701_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quotations',
            name='customer_id',
        ),
    ]
