# Generated by Django 3.0.7 on 2020-07-01 20:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_remove_quotations_customer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotations',
            name='customer_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Customers'),
        ),
    ]
