# Generated by Django 3.0.7 on 2020-07-03 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_quotations_customer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotationsdetails',
            name='quatation_id',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Quotations'),
        ),
    ]
