# Generated by Django 3.0.7 on 2020-07-04 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0012_auto_20200703_2345'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quotations',
            old_name='total_discoutn_percentage',
            new_name='total_discount_percentage',
        ),
    ]
