# Generated by Django 3.0.7 on 2020-07-15 15:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20200706_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_discount_amount', models.FloatField(default=0)),
                ('total_discount_percentage', models.FloatField(default=0)),
                ('total_amount', models.FloatField(default=0)),
                ('net_amount', models.FloatField(default=0)),
                ('remarks', models.CharField(max_length=250)),
                ('delivery', models.CharField(max_length=250)),
                ('payment_remarks', models.CharField(max_length=250)),
                ('invoice_valid', models.CharField(max_length=250)),
                ('lpo_number', models.CharField(max_length=250)),
                ('date', models.DateField(default=datetime.date.today)),
                ('is_updated', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateField(default=datetime.date.today)),
                ('updated_on', models.DateField(null=True)),
                ('deleted_on', models.DateField(null=True)),
                ('customer_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Customers')),
            ],
        ),
        migrations.AlterField(
            model_name='quotations',
            name='remarks',
            field=models.TextField(max_length=250),
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('_type', models.CharField(max_length=250)),
                ('date', models.DateField(default=datetime.date.today)),
                ('remarks', models.CharField(max_length=250)),
                ('is_updated', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateField(default=datetime.date.today)),
                ('updated_on', models.DateField(null=True)),
                ('deleted_on', models.DateField(null=True)),
                ('invoice_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Invoices')),
            ],
        ),
        migrations.CreateModel(
            name='InvoicesDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=250)),
                ('unit', models.IntegerField(default=0)),
                ('rate', models.IntegerField(default=0)),
                ('discount_percentage', models.FloatField(default=0)),
                ('discount_amount', models.FloatField(default=0)),
                ('net_amount', models.FloatField(default=0)),
                ('is_updated', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateField(default=datetime.date.today)),
                ('updated_on', models.DateField(null=True)),
                ('deleted_on', models.DateField(null=True)),
                ('invoice_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Invoices')),
            ],
        ),
    ]
