# Generated by Django 3.0.7 on 2020-07-22 11:02

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20200715_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vouchers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_type', models.CharField(max_length=250)),
                ('date', models.DateField(default=datetime.date.today)),
                ('debit', models.FloatField(default=0)),
                ('credit', models.FloatField(default=0)),
                ('remarks', models.CharField(max_length=250)),
                ('is_updated', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_on', models.DateField(default=datetime.date.today)),
                ('updated_on', models.DateField(null=True)),
                ('deleted_on', models.DateField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='transactions',
            name='voucher_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Vouchers'),
        ),
    ]
