# Generated by Django 3.0.7 on 2020-07-23 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0018_transactions_customer_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vouchers',
            name='date',
        ),
    ]
