# Generated by Django 3.0.7 on 2020-07-23 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_remove_vouchers_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='_type',
            new_name='typeT',
        ),
        migrations.RenameField(
            model_name='vouchers',
            old_name='_type',
            new_name='typeT',
        ),
    ]
