# Generated by Django 3.0.7 on 2020-07-25 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_auto_20200724_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='vouchers',
            name='customer_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dashboard.Customers'),
        ),
    ]
